### ISSUE TITLE
Unable to run Jekyll

### ISSUE THREAD

**Issue by MarMansour** [MarMansour/marwan-mansour-website#1]
Receiving this error message when attempting to run jekyll

   Source: /Users/Marwan
       Destination: /Users/Marwan/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.6.0 | Error:  Operation not supported on socket @ rb_sysopen - /Users/Marwan/Library/Application Support/Adobe/Acrobat/DC/Acrobat/Synchronizer/Commands

@thomasjbradley

**Comment by thomasjbradley** [comment]
Do you have Jekyll running in another terminal window already?

**Comment by MarMansour** [comment]
It doesn't appear so.

**Comment by thomasjbradley** [comment]
Oh, it looks like it’s the wrong directory. Be sure to use "Open in Terminal" from the GitHub app.

**Comment by MarMansour** [comment]
Yup! That was the problem, thank you.
